### ISSUE TITLE
Module not found: Can't resolve '@p5-wrapper/react'

### ISSUE THREAD

**Issue by mechaneyes** [P5-wrapper/next#59]
## Expected Behavior

module is found and sketch loads

## Actual Behavior

Error:

```bash
 ⨯ ./node_modules/@p5-wrapper/next/dist/next.js:886:22
Module not found: Can't resolve '@p5-wrapper/react'
```

## Steps to Reproduce the Problem

1. Create new Next.js app using `npx create-next-app@latest`
2. `yarn add p5 @p5-wrapper/next @p5-wrapper/react`
3. Add typescript example from [README#Usage](https://github.com/P5-wrapper/next?tab=readme-ov-file#usage)
4. Fails to compile and page breaks and throws error, `Module not found: Can't resolve '@p5-wrapper/react'`

## Specifications

Package Versions:

Next.js (14.2.3)

```json
"dependencies": {
  "@p5-wrapper/next": "^1.0.3",
  "@p5-wrapper/react": "^4.4.1",
  "next": "14.2.3",
  "p5": "^1.9.4",
  "react": "^18",
  "react-dom": "^18"
},
```

## Notes

It seems @p5-wrapper/next can't find it's own dependency @p5-wrapper/react.

The peerDependencies within MYAPP/node_modules/@p5-wrapper/next/package.json read as:

```json
"peerDependencies": {
  "@p5-wrapper/react": ">= 4.2.0",
  "next": ">= 12.3.4",
  "react": ">= 18.2.0",
  "react-dom": ">= 18.2.0"
},
```

lines 885-887 in ./node_modules/@p5-wrapper/next/dist/next.js read as:

```js
const Er = /* @__PURE__ */ dr(Rr), Tr = Er(
  async () => (await import("@p5-wrapper/react")).ReactP5Wrapper,
  { ssr: !1 }
);
```

Thanks for your help!

**Comment by bisabi-01** [comment]
Sadly I have the same problem.

**Comment by nickewansmith** [comment]
@bisabi-01 @mechaneyes Maybe try it with `@p5-wrapper/react@^4.4.0`, this works for me with that version. For some reason the 4.4.1 version does not pull a `dist` folder so there is nothing to import.

**Comment by mechaneyes** [comment]
@nickewansmith that did it!

i've implemented that version change in an existing app, and did the same in a freshly setup nextjs app

both worked!

sanity restored. thanks much 🤘🤘

**Comment by bisabi-01** [comment]
> @bisabi-01 @mechaneyes Maybe try it with `@p5-wrapper/react@4.4.0`, this works for me with that version. For some reason the 4.4.1 version does not pull a `dist` folder so there is nothing to import.

I confirm `@p5-wrapper/react@4.4.0` was the way. 
I just had to add `'use client';` at the top of the page and then everything was fine.
Thank you so much :) 👍
